package com.hospital.assistant.model;

public enum IntentName {
    BANDAGE_INTENT,
    BLOOD_PRESSURE_INTENT,
    CATHETER_INTENT,
    DIAPER_INTENT,
    EMERGENCY_INTENT,
    HURTS_INTENT,
    MEDICAL_DRIP_BAG_INTENT,
    PEE_INTENT,
    POOP_INTENT,
    TEMPERATURE_INTENT,
    UTILITY_INTENT,
    WET_UNDER_HAND_INTENT,
    BATHROOM_INTENT
}
